version: '3.8'

services:
  # MySQL
  database:
    image: mysql:8.0.22
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=dev_chat
    ports:
      - 3306:3306
